### ISSUE TITLE
Método equals em Turma

### ISSUE THREAD

**Issue by fabianin** [eliasjnior/prog3rejected#3]
Preciso de um método equals em Turma para saber se quando vou adicionar uma turma a esse aluno aquela turma não já está na lista de turmas dele

**Comment by fabianin** [comment]
Na verdade acho que TODA classe deveria ter um método equals implementado. Só por desencargo de consciência.

**Comment by gustavofsilva** [comment]
Criei na classe Professor os métodos "is". isTurmas() e isDisciplinas(). Que retornar um boolean, verdadeiro se exister, falso caso não exista. Todos que tem uma lista podiam implementar isso ai
